# Generated by Django 5.2 on 2025-04-13 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('is_best_seller', models.BooleanField(default=False)),
                ('pdf_path', models.FileField(blank=True, upload_to='static/pdf')),
                ('publication_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
    ]
