# Generated by Django 5.2 on 2025-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_values',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book_values',
            name='pdf_path',
        ),
        migrations.AddField(
            model_name='book_values',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
