# Generated by Django 5.2 on 2025-04-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_is_best_seller_alter_book_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='book_values',
        ),
    ]
