# Generated by Django 5.2 on 2025-04-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_author_alter_book_values_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_values',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.author'),
        ),
    ]
